### ISSUE TITLE
A way of cancelling scenarios from inside an app

### ISSUE THREAD

**Issue by oskin1** [augustjune/canoe#56]
For now there are methods like `scenario.cancelOn(...)` allowing to cancel scenarios on some user input. But in many cases we need to cancel scenario on some internal event, for example if some service our bot interacts with is unavailiable. 
Is it possible to implement such a method?

**Comment by augustjune** [comment]
`Scenario` is not effect-like type itself (even though it may encapsulate such behavior if `F` is).
This is the reason it is not actually cancelable (it can *finish* if it encounters some particular input - `cancelOn` case).


If you want your scenario to be dependent on the external (for the scenario) state/service, you should construct it in such way. Example:
```scala
val cancelableStuff: F[Either[L, R]] = ???

for {
  e <- Scenario.eval(cancelableStuff)
  r <- e.fold(left => Scenario.done, followingPart)
} yield r
```

If your `F` is interruptible (for example `cats.effect.IO`) you can do something like this:
```scala
val action: IO[A] = ???

for {
  e <- Scenario.eval(action.attempt)
  r <- e.fold(finish, continue)
} yield r
```
where by interrupting your `action` you will finish your scenario as well.

**Comment by oskin1** [comment]
Ok, thank you @augustjune!

**Comment by augustjune** [comment]
Even though the issue is closed, I feel obligated to add one more comment in order to clarify some things stated by me earlier.

> This is the reason it is not actually cancelable

This statement is not true since there's still `cancelOn`/`cancelWith` methods in `Scenario` trait and they were not removed intentionally. 
I was thinking about better naming, but I believe that 'cancel' is actually the best word for describing underlying logic, which is *stop matching the input, discarding current result*. 
However, what I was trying to say in previous comments was that `Scenario` cannot be *interrupted* by the action which is not part of the scenario (at least for now).

I think it doesn't change the answer to the original question but just wanted to provide some context on the existing naming.
